server:
 port:   8001                 # 指定该Eureka-Server的端口
eureka:
 client:
   registerWithEureka: false
   fetchRegistry: false
   serviceUrl:
     defaultZone: http://127.0.0.1:8001/eureka/

spring:
 application:
   name: cloud-register-user

eureka:
 client:
   serviceUrl:
     defaultZone: http://127.0.0.1:8001/eureka/
 instance:
   prefer-ip-address: true





